# Introduction à numpy

In [1]:
import numpy as np

In [2]:
arr1=np.array([2,4,6])
arr1

array([2, 4, 6])

In [3]:
arr1*2

array([ 4,  8, 12])

Générez des arrays remplis de 0 et de 1 de taille 100.


In [4]:
arr2=np.ones(100)
arr3=np.zeros(100)
arr2

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Créez un array bidimensionnel avec des valeurs quelconques, calculer le cube de cet array


In [5]:
arr4=np.array([[2,5,8],[3,5,7]],dtype=float)

In [6]:
arr4**3

array([[   8.,  125.,  512.],
       [  27.,  125.,  343.]])

Construire une matrice rectangulaire de taille 3 x 2 avec une suite de nombres commençant à 5, calculer le produit de la transposée par la matrice.


In [7]:
arr5=np.arange(5,11).reshape(3,2)

In [8]:
print(np.dot(arr5.T,arr5))

[[155 176]
 [176 200]]


Générer un array de nombres aléatoires puis remplacer les valeurs plus petites que 0 par 0. Trier l’array obtenu


In [9]:
arr6=np.random.randn(1000000)
arr6

array([ 1.36571593,  0.50360976,  1.02623017, ..., -0.88437297,
       -1.1450082 , -0.01236275])

In [10]:
np.mean(arr6)

0.0001922746670383864

In [11]:
np.var(arr6)

0.99943742812256209

In [12]:
arr7=np.where(arr6<0,0,arr6)
np.mean(arr7)

0.39880564885812703

In [13]:
np.min(arr7)

0.0

In [14]:
np.max(arr7)

5.1458913383149287

In [15]:
%whos

Variable   Type       Data/Info
-------------------------------
arr1       ndarray    3: 3 elems, type `int32`, 12 bytes
arr2       ndarray    100: 100 elems, type `float64`, 800 bytes
arr3       ndarray    100: 100 elems, type `float64`, 800 bytes
arr4       ndarray    2x3: 6 elems, type `float64`, 48 bytes
arr5       ndarray    3x2: 6 elems, type `int32`, 24 bytes
arr6       ndarray    1000000: 1000000 elems, type `float64`, 8000000 bytes (7.62939453125 Mb)
arr7       ndarray    1000000: 1000000 elems, type `float64`, 8000000 bytes (7.62939453125 Mb)
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


Sauvegardez des arrays

In [16]:
arr9=np.random.randn(10000000).reshape(1000000,10)

In [17]:
arr9.shape

(1000000, 10)

In [18]:
np.save("arr9",arr9)

In [19]:
del arr9

In [20]:
arr9=np.load("arr9.npy")

In [21]:
np.savetxt("arr9.txt",arr9)