# Machine Learning

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

### Régression linéaire

In [8]:
#on importe les données
frame_adv=pd.read_csv("Advertising.csv",index_col=0)
frame_adv.head()

TV  Radio  Newspaper  Sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

Régressions avec statsmodels

In [20]:
from statsmodels.formula.api import ols
from statsmodels.formula.api import logit

In [9]:
#on ajuste directement le modèle
modele_ols1=ols("Sales ~ TV+Radio+Newspaper",data=frame_adv).fit()

In [11]:
modele_ols1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Fri, 23 Jun 2017   Prob (F-statistic):           1.58e-96
Time:                        13:57:26   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.9389      0.312      9.422      0.000       2.324       3.554
TV             0.0458      0.001     32.809      0.000       0.043       0.049
Radio          0.1885      0.009     21.893      0.000       0.172       0.206
Newspaper     -0.0010      0.006     -0.177      0.860      -0.013       0.011
==============================================================================
Omnibus:                       60.414   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              151.241
Skew:                          -1.327   Prob(JB):                     1.44e-33
Kurtosis:                       6.332   Cond. No.                         454.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [13]:
#on crée une nouvelle variable binaire
frame_adv["Sales0"]=np.where(frame_adv["Sales"]<frame_adv["Sales"].mean(),
                            0,1)

In [15]:
#on ajuste un modèle logistique
modele_logit1=logit("Sales0 ~ TV+Radio+Newspaper",data=frame_adv).fit()

Optimization terminated successfully.
         Current function value: 0.116643
         Iterations 10


In [19]:
modele_logit1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                 Sales0   No. Observations:                  200
Model:                          Logit   Df Residuals:                      196
Method:                           MLE   Df Model:                            3
Date:                Fri, 23 Jun 2017   Pseudo R-squ.:                  0.8302
Time:                        14:05:47   Log-Likelihood:                -23.329
converged:                       True   LL-Null:                       -137.42
                                        LLR p-value:                 3.428e-49
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -22.3384      4.773     -4.680      0.000     -31.694     -12.983
TV             0.0791      0.017      4.716      0.000       0.046       0.112
Radio          0.4275      0.092      4.660      0.000       0.248       0.607
Newspaper     -0.0080      0.018     -0.453      0.650      -0.042       0.026
==============================================================================

Possibly complete quasi-separation: A fraction 0.39 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

### Régressions avec scikit-learn

In [21]:
from sklearn.linear_model import LinearRegression

In [25]:
#préparer les données
y=frame_adv["Sales"]
x=frame_adv[["TV","Radio","Newspaper"]]

In [28]:
#construire un objet modele vide
modele_ols2=LinearRegression()

In [27]:
#ajuster le modèle (on introduit ici les données dans le modèle)
modele_ols2.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [31]:
#on affiche les résultats
modele_ols2.coef_

array([ 0.04576465,  0.18853002, -0.00103749])

In [32]:
modele_ols2.intercept_

2.9388893694594085

In [33]:
#on affiche les prédictions
modele_ols2.predict(x)

array([ 20.52397441,  12.33785482,  12.30767078,  17.59782951,
        13.18867186,  12.47834763,  11.72975995,  12.12295317,
         3.72734086,  12.55084872,   7.0322992 ,  17.28512918,
        10.57712073,   8.82630048,  18.43436638,  20.81929952,
        12.82365674,  23.22495716,   9.95168206,  14.16607293,
        18.10076728,  14.7405382 ,   6.4891503 ,  16.5459329 ,
         8.14651887,  15.6100386 ,  14.98951429,  17.05167344,
        19.41053803,   9.14402389,  21.6339338 ,  11.3460929 ,
         7.63888314,  18.86426829,   7.57483051,  17.00682618,
        23.40590052,  15.62347779,   9.90868103,  20.44761039,
        16.37766467,  17.2959832 ,  21.59580326,  13.96385684,
         8.88787996,  15.16152314,   8.87338673,  21.7226299 ,
        16.26362018,   8.1681656 ,  12.63121132,   9.33981296,
        20.66297563,  19.94469957,  20.37443008,  21.2926106 ,
         8.52771254,  12.77458802,  21.89805198,  18.13348698,
         5.74215558,  22.89067208,  16.78426073,  13.21

In [34]:
from sklearn.metrics import mean_squared_error

In [35]:
#calculer le MSE
mean_squared_error(y,modele_ols2.predict(x))

2.7841263145109365

### k-plus proches voisins

In [36]:
from sklearn.neighbors import KNeighborsClassifier

In [39]:
#importer et préparer les données
frame_churn = pd.read_csv("telecom.csv")
frame_churn.head()

State  Account Length  Area Code     Phone Int'l Plan VMail Plan  \
0    KS             128        415  382-4657         no        yes   
1    OH             107        415  371-7191         no        yes   
2    NJ             137        415  358-1921         no         no   
3    OH              84        408  375-9999        yes         no   
4    OK              75        415  330-6626        yes         no   

   VMail Message  Day Mins  Day Calls  Day Charge   ...    Eve Calls  \
0             25     265.1        110       45.07   ...           99   
1             26     161.6        123       27.47   ...          103   
2              0     243.4        114       41.38   ...          110   
3              0     299.4         71       50.90   ...           88   
4              0     166.7        113       28.34   ...          122   

   Eve Charge  Night Mins  Night Calls  Night Charge  Intl Mins  Intl Calls  \
0       16.78       244.7           91         11.01       10.0           3   
1       16.62       254.4          103         11.45       13.7           3   
2       10.30       162.6          104          7.32       12.2           5   
3        5.26       196.9           89          8.86        6.6           7   
4       12.61       186.9          121          8.41       10.1           3   

   Intl Charge  CustServ Calls  Churn?  
0         2.70               1  False.  
1         3.70               1  False.  
2         3.29               0  False.  
3         1.78               2  False.  
4         2.73               3  False.  

[5 rows x 21 columns]

In [40]:
#on construit une nouvelle variable
frame_churn["churn"]=np.where(frame_churn["Churn?"]=="False.",0,1)

In [42]:
frame_churn["churn"].value_counts()

0    2850
1     483
Name: churn, dtype: int64

In [43]:
y=frame_churn["churn"]

In [58]:
#on récupère les variables quanti dans X
x=frame_churn.select_dtypes(include=[np.number])

In [59]:
#on enlève churn de X
x.drop("churn",axis=1,inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [60]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 16 columns):
Account Length    3333 non-null int64
Area Code         3333 non-null int64
VMail Message     3333 non-null int64
Day Mins          3333 non-null float64
Day Calls         3333 non-null int64
Day Charge        3333 non-null float64
Eve Mins          3333 non-null float64
Eve Calls         3333 non-null int64
Eve Charge        3333 non-null float64
Night Mins        3333 non-null float64
Night Calls       3333 non-null int64
Night Charge      3333 non-null float64
Intl Mins         3333 non-null float64
Intl Calls        3333 non-null int64
Intl Charge       3333 non-null float64
CustServ Calls    3333 non-null int64
dtypes: float64(8), int64(8)
memory usage: 416.7 KB


In [61]:
from sklearn.model_selection import train_test_split

In [110]:
#fixer la graine
np.random.seed(12)

In [111]:
#séparation apprentissage / test
x_train, x_test, y_train, y_test =train_test_split(x,y,test_size=0.2)

In [112]:
#créer un modèle
modele_knn1=KNeighborsClassifier(n_neighbors=10)

In [113]:
#on ajuste le modèle
modele_knn1.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=10, p=2,
           weights='uniform')

In [114]:
from sklearn.metrics import confusion_matrix, recall_score, accuracy_score
from sklearn.metrics import roc_auc_score

In [115]:
#on affiche la matrice de confusion
confusion_matrix(y_test,modele_knn1.predict(x_test))

array([[575,   3],
       [ 75,  14]])

In [116]:
#on affiche le % de bien classés
accuracy_score(y_test,modele_knn1.predict(x_test))

0.88305847076461774

In [117]:
#on affiche le recall
recall_score(y_test,modele_knn1.predict(x_test))

0.15730337078651685

### SVM et Random Forrest

In [118]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [132]:
modele_svm=SVC()
modele_rf=RandomForestClassifier(n_estimators=1000)

In [135]:
modele_svm.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [133]:
modele_rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=1000, n_jobs=1, oob_score=False,
            random_state=None, verbose=0, warm_start=False)

In [136]:
print("Accuracy pour les SVM :" ,accuracy_score(y_test,
                                                modele_svm.predict(x_test)))
print("Accuracy pour les RF :" ,accuracy_score(y_test,
                                                modele_rf.predict(x_test)))
print("Accuracy pour les kNN :" ,accuracy_score(y_test,
                                                modele_knn1.predict(x_test)))

Accuracy pour les SVM : 0.866566716642
Accuracy pour les RF : 0.931034482759
Accuracy pour les kNN : 0.883058470765


In [137]:
print("Mat de conf pour les SVM :" ,confusion_matrix(y_test,
                                                modele_svm.predict(x_test)),sep="\n")
print("Mat de conf pour les RF :" ,confusion_matrix(y_test,
                                                modele_rf.predict(x_test)),sep="\n")
print("Mat de conf pour les kNN :" ,confusion_matrix(y_test,
                                                modele_knn1.predict(x_test)),
     sep="\n")

Mat de conf pour les SVM :
[[578   0]
 [ 89   0]]
Mat de conf pour les RF :
[[573   5]
 [ 41  48]]
Mat de conf pour les kNN :
[[575   3]
 [ 75  14]]


### Définir les hyper-paramètres

In [138]:
from sklearn.grid_search import GridSearchCV

In [144]:
#recherche des meilleurs paramètres
modele_gridrf=GridSearchCV(modele_rf,
                           param_grid={"n_estimators":[10,100,1000],
                                   "max_depth":[None,10]},
                        scoring="recall")

In [145]:
#ajustement du modèle
modele_gridrf.fit(x,y)

GridSearchCV(cv=None, error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=1000, n_jobs=1, oob_score=False,
            random_state=None, verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_estimators': [10, 100, 1000], 'max_depth': [None, 10]},
       pre_dispatch='2*n_jobs', refit=True, scoring='recall', verbose=0)

In [147]:
#affichage des meilleurs paramètres
modele_gridrf.best_params_

{'max_depth': None, 'n_estimators': 100}

In [148]:
modele_gridrf.best_score_

0.5403726708074534